# Generated by Django 3.0.8 on 2020-08-04 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200724_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('4b4a973b-dbe5-44eb-8f61-b527d49765a5'), max_length=100, unique=True),
        ),
    ]
