# Generated by Django 3.0.8 on 2020-08-11 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200804_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associateaccount',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrganisationAccount'),
        ),
        migrations.AlterField(
            model_name='associateaccount',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ManagerAccount'),
        ),
        migrations.AlterField(
            model_name='manageraccount',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrganisationAccount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('735fe8b9-27af-4e22-9c73-4eaed1c2f92f'), max_length=100, unique=True),
        ),
    ]
