# Generated by Django 3.0.8 on 2020-07-13 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200713_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('fd15b474-bf43-48a3-9660-617f8b81cd86'), max_length=100, unique=True),
        ),
    ]
