# Generated by Django 3.0.8 on 2020-08-11 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200811_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associateaccount',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OrganisationAccount'),
        ),
        migrations.AlterField(
            model_name='associateaccount',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ManagerAccount'),
        ),
        migrations.AlterField(
            model_name='manageraccount',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OrganisationAccount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('5c1f2f0f-8928-4537-8089-000baa92321c'), max_length=100, unique=True),
        ),
    ]
