# Generated by Django 3.0.8 on 2021-03-03 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200811_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('b5eb4dfb-5f68-4796-8a71-a6034f0ba49d'), max_length=100, unique=True),
        ),
    ]
