# Generated by Django 3.0.8 on 2021-03-03 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210303_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('6f25f8ab-7d07-49af-b38a-d41c5ff6d439'), max_length=100, unique=True),
        ),
    ]
