# Generated by Django 3.0.8 on 2021-03-03 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210303_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.UUID('79b7a74d-8126-4061-bcbd-ea7b6956d3ec'), max_length=100, unique=True),
        ),
    ]
