# Generated by Django 3.1b1 on 2020-06-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('project_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('analysis', models.BooleanField(default=False)),
                ('analysis_text', models.TextField(default='')),
                ('cut', models.BooleanField(default=False)),
                ('cut_text', models.TextField(default='')),
                ('code_merge', models.BooleanField(default=False)),
                ('code_merge_text', models.TextField(default='')),
                ('ST', models.BooleanField(default=False)),
                ('ST_text', models.TextField(default='')),
                ('UAT', models.BooleanField(default=False)),
                ('UAT_text', models.TextField(default='')),
                ('implementation', models.BooleanField(default=False)),
                ('implementation_text', models.TextField(default='')),
                ('PIS', models.BooleanField(default=False)),
                ('PIS_text', models.TextField(default='')),
                ('assoc_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmetadata')),
            ],
        ),
    ]
